baseURL: https://crazymax.dev/
languageCode: en-us
title: CrazyMax
canonifyurls: true
enableRobotsTXT: true
googleAnalytics: UA-12516800-8
disqusShortname: does-not-exist
enableEmoji: true

module:
  imports:
    - path: github.com/hugo-toha/toha

theme:
  - toha

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false
