name: website

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          submodules: true
      -
        name: Hugo
        uses: crazy-max/ghaction-hugo@v1
        with:
          version: latest
          extended: true
          args: --cleanDestinationDir --minify --verbose
      -
        name: Check GitHub Pages status
        uses: crazy-max/ghaction-github-status@v2
        with:
          pages_threshold: major_outage
      -
        name: Deploy
        if: success() && github.event_name != 'pull_request'
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: master
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
