name: website

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      -
        # https://github.com/actions/checkout
        name: Checkout
        uses: actions/checkout@v1
      -
        # https://github.com/crazy-max/ghaction-hugo
        name: Hugo
        uses: crazy-max/ghaction-hugo@v1
        with:
          version: latest
          args: --cleanDestinationDir --minify --verbose
      -
        # https://github.com/crazy-max/ghaction-github-pages
        name: Deploy
        if: success() && github.event_name != 'pull_request'
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: master
          build_dir: public
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
